manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.3.0
      path: zephyr
      # 👇 ESTA línea es la clave para que aparezca `west build`
      west-commands: scripts/west-commands.yml

  self:
    path: motor-sim-demo

