manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.3.0
      path: zephyr
      # This line enables extra `west` commands such as `west build`.
      west-commands: scripts/west-commands.yml

  self:
    path: motor-sim-demo

